// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VKITActivityManager.Models;

#nullable disable

namespace VKITActivityManager.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260525073218_AddBangHocPhi")]
    partial class AddBangHocPhi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VKITActivityManager.Models.HoatDong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DuongDanAnh")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DuongDanAnh");

                    b.Property<string>("DuongDanVideo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DuongDanVideo");

                    b.Property<string>("MoTaNgan")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MoTaNgan");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NoiDung");

                    b.Property<int>("PhanLoai")
                        .HasColumnType("int")
                        .HasColumnName("PhanLoai");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TieuDe");

                    b.Property<string>("TieuDe2")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TieuDe2");

                    b.HasKey("Id");

                    b.ToTable("HoatDong");
                });

            modelBuilder.Entity("VKITActivityManager.Models.HocPhi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DonViApDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HocPhiGiam25")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HocPhiGiam50")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LaDongPhu")
                        .HasColumnType("bit");

                    b.Property<string>("MucHocPhi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NganhDaoTao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThoiGian")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DanhSachHocPhi");
                });
#pragma warning restore 612, 618
        }
    }
}
