// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VKITActivityManager.Models;

#nullable disable

namespace VKITActivityManager.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260603014515_ThêmPhanLoaiChatbox")]
    partial class ThêmPhanLoaiChatbox
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VKITActivityManager.Models.AnhUuDiem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DuongDanAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTaNgan")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("UuDiemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UuDiemId");

                    b.ToTable("AnhUuDiems");
                });

            modelBuilder.Entity("VKITActivityManager.Models.CauHoiThuongGap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CauHoi")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("PhanLoai")
                        .HasColumnType("int");

                    b.Property<string>("TraLoi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CauHoiThuongGaps");
                });

            modelBuilder.Entity("VKITActivityManager.Models.ChuyenNganh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenNganh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ChuyenNganh");
                });

            modelBuilder.Entity("VKITActivityManager.Models.HoatDong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DuongDanAnh")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DuongDanAnh");

                    b.Property<string>("DuongDanVideo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DuongDanVideo");

                    b.Property<string>("MoTaNgan")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MoTaNgan");

                    b.Property<int?>("NganhId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NoiDung");

                    b.Property<int>("PhanLoai")
                        .HasColumnType("int")
                        .HasColumnName("PhanLoai");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TieuDe");

                    b.Property<string>("TieuDe2")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TieuDe2");

                    b.HasKey("Id");

                    b.ToTable("HoatDong");
                });

            modelBuilder.Entity("VKITActivityManager.Models.HoatDongChuyenNganh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChuyenNganhId")
                        .HasColumnType("int");

                    b.Property<string>("DuongDanAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDePhu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChuyenNganhId");

                    b.ToTable("HoatDongChuyenNganh");
                });

            modelBuilder.Entity("VKITActivityManager.Models.HocPhi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DonViApDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeDaoTao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HocPhiGiam25")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HocPhiGiam50")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LaDongPhu")
                        .HasColumnType("bit");

                    b.Property<string>("MucHocPhi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NganhDaoTao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThoiGian")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DanhSachHocPhi");
                });

            modelBuilder.Entity("VKITActivityManager.Models.LoaiHocBong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MauNen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoSuat")
                        .HasColumnType("int");

                    b.Property<string>("TenHocBong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LoaiHocBong");
                });

            modelBuilder.Entity("VKITActivityManager.Models.PhanLoaiVideo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenPhanLoai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("PhanLoaiVideos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TenPhanLoai = "Video Giới thiệu (Toàn màn hình)"
                        },
                        new
                        {
                            Id = 2,
                            TenPhanLoai = "Video Danh sách (Ngang ở dưới)"
                        });
                });

            modelBuilder.Entity("VKITActivityManager.Models.SinhVienHocBong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LoaiHocBongId")
                        .HasColumnType("int");

                    b.Property<string>("Lop")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaSV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayNhan")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenSinhVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LoaiHocBongId");

                    b.ToTable("SinhVienHocBong");
                });

            modelBuilder.Entity("VKITActivityManager.Models.UuDiem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MauNen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenUuDiem")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("UuDiems");
                });

            modelBuilder.Entity("VKITActivityManager.Models.Video", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DuongDanVideo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTaNgan")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("PhanLoaiVideoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PhanLoaiVideoId");

                    b.ToTable("Videos");
                });

            modelBuilder.Entity("VKITActivityManager.Models.AnhUuDiem", b =>
                {
                    b.HasOne("VKITActivityManager.Models.UuDiem", "UuDiem")
                        .WithMany("DanhSachHinhAnh")
                        .HasForeignKey("UuDiemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UuDiem");
                });

            modelBuilder.Entity("VKITActivityManager.Models.HoatDongChuyenNganh", b =>
                {
                    b.HasOne("VKITActivityManager.Models.ChuyenNganh", "ChuyenNganh")
                        .WithMany("HoatDongChuyenNganhs")
                        .HasForeignKey("ChuyenNganhId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChuyenNganh");
                });

            modelBuilder.Entity("VKITActivityManager.Models.SinhVienHocBong", b =>
                {
                    b.HasOne("VKITActivityManager.Models.LoaiHocBong", "LoaiHocBong")
                        .WithMany("SinhVienHocBongs")
                        .HasForeignKey("LoaiHocBongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiHocBong");
                });

            modelBuilder.Entity("VKITActivityManager.Models.Video", b =>
                {
                    b.HasOne("VKITActivityManager.Models.PhanLoaiVideo", "PhanLoaiVideo")
                        .WithMany("Videos")
                        .HasForeignKey("PhanLoaiVideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhanLoaiVideo");
                });

            modelBuilder.Entity("VKITActivityManager.Models.ChuyenNganh", b =>
                {
                    b.Navigation("HoatDongChuyenNganhs");
                });

            modelBuilder.Entity("VKITActivityManager.Models.LoaiHocBong", b =>
                {
                    b.Navigation("SinhVienHocBongs");
                });

            modelBuilder.Entity("VKITActivityManager.Models.PhanLoaiVideo", b =>
                {
                    b.Navigation("Videos");
                });

            modelBuilder.Entity("VKITActivityManager.Models.UuDiem", b =>
                {
                    b.Navigation("DanhSachHinhAnh");
                });
#pragma warning restore 612, 618
        }
    }
}
